Updated Fully

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,6 +4,7 @@ on:
     branches: [main]
   pull_request:
     branches: [main]
+
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -12,6 +13,7 @@ jobs:
         image: mongo:4.4
         ports:
           - 27017:27017
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -26,9 +28,10 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
-    - name: Set PYTHONPATH
+    - name: List all files and paths
       run: |
-        echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/testselenium/configfile" >> $GITHUB_ENV
+        echo "Listing all files and paths in the repository:"
+        find . -type f
 
     - name: Set Environment Variables
       run: |
@@ -42,20 +45,45 @@ jobs:
           sleep 1
         done
         echo "MongoDB is ready"
+
     - name: Configure MongoDB Test Data
       run: |
-        python configfile/config.py  # Adjust the path to your setup script if necessary
+        python configfile/config.py
+
     - name: Set up ChromeDriver and Chrome
       uses: browser-actions/setup-chrome@v1
       with:
         chrome-version: 'latest'
-    - name: Run Selenium Tests
+
+    - name: Set Timezone to India Standard Time (IST)
+      run: sudo timedatectl set-timezone Asia/Kolkata
+
+    - name: Run Selenium tests and generate HTML report
+      id: run_tests
       run: |
-        python -m unittest discover -s login_testcases -p "valid.py"
+        pytest --html=report.html --self-contained-html > pytest_test_results.log || exit 0
+        cat pytest_test_results.log
 
+    - name: Check if tests passed
+      id: check_tests
+      run: |
+        if grep -q "FAILED" pytest_test_results.log; then
+          echo "Tests failed"
+          echo "TESTS_PASSED=false" >> $GITHUB_ENV
+        else
+          echo "Tests passed"
+          echo "TESTS_PASSED=true" >> $GITHUB_ENV
 
+    
 
+    - name: Archive Pytest Results
+      uses: actions/upload-artifact@v3
+      with:
+              name: pytest-results
+              path: pytest_test_results.log
 
-
-
-
+    - name: Archive HTML Test Report
+      uses: actions/upload-artifact@v3
+      with:
+        name: selenium-test-report
+        path: report.html
